# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Search-Pagesjaunes
version:      0.13
version_from: lib/WWW/Search/Pagesjaunes.pm
installdirs:  site
requires:
    HTML::Form:                    0
    HTML::TokeParser:              0
    LWP::UserAgent:                1.8
    Pod::Usage:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
